### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by ksobon** [CAAD-RWTH/ClockworkForDynamo#12]
Andy, If possible did you think about posting the source code for all nodes as well? I am talking especially about nodes that have custom Python nodes. It's just easier to contribute when one can see the code clearly instead of in context of a *.dyf file formatting.

**Comment by andydandy74** [comment]
That's actually a really nice idea - but also a lot of work considering the number of nodes that actually contain some Python code. I will most likely not be able to do that before summer. Maybe it makes more sense trying to automate this - I built a very basic DYN file parser a while back to correct screwed up node coordinates, maybe I can re-use that...

**Comment by andydandy74** [comment]
Done. @ksobon - this was way easier than I had imagined.
Python scripts can now be found here: https://github.com/CAAD-RWTH/ClockworkForDynamo/tree/master/nodes/0.7.x/python
And the tool to extract them here:
https://github.com/CAAD-RWTH/ClockworkForDynamo/tree/master/workflow_samples/0.7.x/ExtractPythonScripts
I imagine this graph would not work well for files that contain multiple Python scripts, but I don't think I have that in any of my nodes.
