### ISSUE TITLE
Rework Room.DoorsOrWindows

### ISSUE THREAD

**Issue by andydandy74** [CAAD-RWTH/ClockworkForDynamo#30]
- Reconsider dividing this into two separate nodes or use a boolean switch instead of a category input
- For processing multiple rooms this currently has to be used in conjunction with a List.Map node - not so comfy

**Comment by andydandy74** [comment]
Thi snode can now process a list of rooms without having to use List.Map, but we'll stick with the category input for now.

**Comment by andreabotti** [comment]
@andydandy74 I have spotted your useful answers in this [post]:(http://dynamobim.org/forums/topic/rooms-doorsorwindows-explanation/).

However, I cannot make the script work (plus I am using Dynamo0.9 + Clockwork 0.9.7 and Room.DoorsOrWindows is not available anymore.

![error_doors-windows_2016 08 05](https://cloud.githubusercontent.com/assets/19609643/17440883/72848772-5b26-11e6-9cfc-639327851bc6.JPG)
