### ISSUE TITLE
View.Plane node

### ISSUE THREAD

**Issue by josols** [CAAD-RWTH/ClockworkForDynamo#38]
The View.Plane node doesn't regenerate when I hit run after I've moved a section in the Revit document. Is this intentional?

**Comment by andydandy74** [comment]
Hi @josols - definitely not intentional. Will have to investigate...

**Comment by ksobon** [comment]
@josols @andydandy74 this is standard Dynamo problem. Everyone has that same issue. I have been going by this by adding a Boolean Toggle to my nodes and you would have to toggle it on/off. The whole problem is that the input to python nodes need to be different for it to be re-executed and moving something in Revit doesn't really set off re-generation.

**Comment by josols** [comment]
I've hacked around achieving something like this:
![slett meg](https://cloud.githubusercontent.com/assets/7080648/7833932/01f67a0a-046b-11e5-99b5-60365202220a.png)

And just adding an input which does nothing to the pythonscript in your node, Andreas. 

I tried to include the three nodes into a the view.plane node itself, and Dynamo gives the possibility to run periodic, but it doesn't work..

So I guess Konrads solution is more viable for now.

**Comment by andydandy74** [comment]
I think I'll turn this into a feature request for the Dynamo team. We need to be able to set Python-based custom nodes to force-execute each time a graph runs. Both your solutions are viable but it feels like jumping through hoops.

**Comment by andydandy74** [comment]
Created a feature request here:
https://github.com/DynamoDS/Dynamo/issues/4603
Let's see what happens...

**Comment by andydandy74** [comment]
I am closing this for now as I don't plan on coding around a built-in limitation of Dynamo.
