### ISSUE TITLE
List.ChopByLengths not taking lengths list with just one item.

### ISSUE THREAD

**Issue by Xavorithre** [CAAD-RWTH/ClockworkForDynamo#39]
The List.ChopByLengths node doesn't seem to like it when I put in a number instead of a list of numbers (part 1). Also it doesn't flatten the list when the length of the input list is equal to the given number (part 2).
Now you might wonder why I use this node then. That's because sometimes the the lengths input is, and sometimes it isn't, just one single number. Of course it does work when I put in several numbers, I would just like it to work with a single number out of the box, too. :)
![image](https://cloud.githubusercontent.com/assets/12560387/7771255/4c22f05a-0096-11e5-9a86-f025c5d54114.png)

**Comment by andydandy74** [comment]
Both of these issues are easy to solve by integrating ```Turn Into List``` and ```ReturnListOrSingleValue``` nodes into the ```List.ChopByLengths``` node. This improvement will be part of the next package update. Thanks for reporting, @Xavorithre
