### ISSUE TITLE
Element.ParameterExists in 0.8.1

### ISSUE THREAD

**Issue by formula1210204** [CAAD-RWTH/ClockworkForDynamo#41]
This node seems not working in Dynamo 0.8.1, I will go back to 0.8.0 since it's use in my daily work, just let you know the issue.
 Thanks for your great works!

**Comment by andydandy74** [comment]
Thanks for reporting, @formula1210204 - I'll have a look at this once I start migrating Clockwork to Dynamo 0.8 (which will probably not happen before late summer).

**Comment by ksobon** [comment]
please see this: https://github.com/CAAD-RWTH/ClockworkForDynamo/pull/59

**Comment by andydandy74** [comment]
thanks again @ksobon !
@formula1210204  - this will be in the next release of Clockwork.
