### ISSUE TITLE
Filter.ByInstParamValue

### ISSUE THREAD

**Issue by jbenoit44** [CAAD-RWTH/ClockworkForDynamo#45]
In the CN, I've edited my local dyf to use A equal B instead of ==, it allows me to use object comparison (like phases). not tested any further with strings though....

**Comment by andydandy74** [comment]
Are you sure this is one of mine? 

If it is, that node doesn't exist anymore in Clockwork. I think I turned this into Elements.FilterByParameterValueAndCondition in order to have the comparator outside of the CN.

**Comment by jbenoit44** [comment]
right!! this is not yours.
