### ISSUE TITLE
suggestion: Rename "DetailCurve.FromCurve"

### ISSUE THREAD

**Issue by dimven** [CAAD-RWTH/ClockworkForDynamo#49]
Renaming the node to "DetailLine.FromCurve" could possibly make it easier to find for new users.

**Comment by andydandy74** [comment]
You're right @dimven - DetailCurve is typical API speak. I sooo wish we had search keywords for custom nodes...

**Comment by andydandy74** [comment]
This will be renamed in the 0.8 version of Clockwork
