### ISSUE TITLE
Clipboard.GetFrom not working in 0.8

### ISSUE THREAD

**Issue by andydandy74** [CAAD-RWTH/ClockworkForDynamo#54]
~~Neither one of the clipboard nodes is working.~~ **```Clipboard.GetFrom``` simply returns nothing** ~~while ```Clipboard.SendTo``` returns the following error:
Warnung:IronPythonEvaluator.EvaluateIronPythonScript fehlgeschlagen.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
SystemError: Für den aktuellen Thread muss der STA-Modus (Single Thread Apartment) festgelegt werden, bevor OLE-Aufrufe ausgeführt werden können. Stellen Sie sicher, dass die Hauptfunktion mit STAThreadAttribute gekennzeichnet ist.~~

**Comment by dimven** [comment]
I was wondering why this node has disappeared. I had a similar problem with my drag-drop reordering node and solved it as described here:
http://www.ironpython.info/index.php?title=Setting_the_Clipboard

You can find the SN node here:
https://github.com/dimven/SpringNodes/blob/master/Nodes/List.DragDropReorder.dyf

**Comment by andydandy74** [comment]
@dimven - Thanks! This does indeed work for sending stuff to the clipboard. Now I'll have to see how I can apply this to retrieving the clipboard contents.

**Comment by dimven** [comment]
Same thing. But because we're nesting functions, we'll need to call a global variable first:
![dynamosandbox_2016-01-20_20-55-58](https://cloud.githubusercontent.com/assets/7148394/12449449/52e6b638-bfb8-11e5-8739-d1c83acf0ea4.png)

**Comment by andydandy74** [comment]
Thanks @dimven
