### ISSUE TITLE
Room.DoorsOrWindows

### ISSUE THREAD

**Issue by ksobon** [CAAD-RWTH/ClockworkForDynamo#58]
Can you explain to me what the purpose of this node is? What should it return? I looked under the hood and god forbid, but that thing is like Inception with so many levels that I was afraid I could not get out of it. :-) Hahahah, someone made a comment about it, that it should work with lists so i thought i look at it but i was immediately scared off by all of the dependencies and levels of nested custom nodes. Sorry man. I am not a fan.

**Comment by andydandy74** [comment]
:-)
Yeah, I should probably just do this one entirely in Python - that would be a **lot** less code.

**Comment by andydandy74** [comment]
simplified the node a little...
