### ISSUE TITLE
Allow SINGLE rotation value for TextNote.ByStringAndPosition

### ISSUE THREAD

**Issue by buddyd16** [CAAD-RWTH/ClockworkForDynamo#76]
I am unable to get the TextNote.ByStringAndPosition node to work I have tried everything I can think of even using individual code blocks to each of the inputs with the same result (see attached jpg).

any help would be great...normally would put this on the dynamo forum but its in the middle of a transition.

Revit 2014
Dynamo 0.8.2.2392
Clockwork for Dynamo 0.8.2

![capture](https://cloud.githubusercontent.com/assets/12416202/10948359/32e32a5a-82fb-11e5-885e-b860b694b2bc.JPG)

**Comment by buddyd16** [comment]
I was able to get the underlying python code of the node to work as its own python node and switching out rotation with the x and z vectors in a list that matches the size of my string and point lists.

**Comment by andydandy74** [comment]
In its current state, the node expects a list of angles for the rotation input. I can see that for a lot of cases it would make sense to have this as an optional feature instead of as a default. I'll redesign the node accordingly.

**Comment by buddyd16** [comment]
Andy,

thanks for the info. Can the same be said for the "width" input is it also looking for a list of widths rather than a single width input.

Also for my own education where is the best place to get documentation on each of the nodes you have provided, not very familiar with git hubs layout.

Thank you

**Comment by andydandy74** [comment]
:-) I may have been a bit overenthusiastic when making this node. I think I will revert the width input to expect a single item instead of a list.

Regarding documentation:
There are samples for the operation of almost all of the Clockwork nodes in this directory: https://github.com/CAAD-RWTH/ClockworkForDynamo/tree/master/package_samples/0.7.x
Not all of this is up-to-date, though, and it's highly unlikely that I will manage to update the samples before next summer.

**Comment by buddyd16** [comment]
Ha no worries.... the obviously hard work in creating all these supplementary nodes is much appreciated. 

Thanks for the link to the sample files as well.

**Comment by andydandy74** [comment]
@buddyd16 - I will close this for now, but I plan to rewrite this node as a Zero Touch node in 2016 (#85) which would make it a lot more flexible in terms of feeding list *or* single elements into *any* of the inputs.
