### ISSUE TITLE
Automation with latest build + CW 0.9

### ISSUE THREAD

**Issue by jbenoit44** [CAAD-RWTH/ClockworkForDynamo#77]
![image](https://cloud.githubusercontent.com/assets/4572196/10982028/53da81ac-840b-11e5-8e78-e40cda126161.png)

**Comment by andydandy74** [comment]
@jbenoit44 - Can you describe the problem?

**Comment by jbenoit44** [comment]
Automation pck ask for CW 0.9 uninstall. 
J BENOIT
Le 6 nov. 2015 06:31, Andreas Dieckmann <notifications@github.com> a écrit :@jbenoit44 - Can you describe the problem?

**Comment by andydandy74** [comment]
Did you have Clockwork installed before you installed DynamoAutomation?

**Comment by andydandy74** [comment]
I am closing this for now. Feel free to re-open.
