### ISSUE TITLE
Get empty lists

### ISSUE THREAD

**Issue by arkdanielnielsen** [CAAD-RWTH/ClockworkForDynamo#78]
Hi @andydandy74 
For some strange reason the Clockwork nodes returns empty list. It works on my laptop at work but my home laptop it does not work. It have worked previously, but not anymore.
I have tried to install a older 9.1 version of Dynamo (DynamoInstall0.9.1.20151026T1255) to check if that were the problem, but same result. I have also tried to re-install Clockwork and still empty lists. Further I also checked if some of the nodes were blocked, and no one were blocked. And last I have tried with both Revit 2015 and 2016 just to check if that had any influence. 
I do not know if it is a Clockwork problem or a Dynamo problem. Have you any wierd experience with this types of problems?
Thanks :)
![clockwork01](https://cloud.githubusercontent.com/assets/7299731/11014899/d3c93dce-8549-11e5-8d47-11890b41ac60.JPG)

**Comment by andydandy74** [comment]
It looks like you're using an older version of Clockwork, probably Clockwork for Dynamo 0.7.x ...
You should uninstall that package and install Clockwork for Dynamo 0.9.x
Please re-open if that doesn't solve your issue.

**Comment by arkdanielnielsen** [comment]
Thanks it worked! I though I had tried that. 
I see some functionalities is change in the node "WallType.Kind". Before it returned values instead of names (like: Basic [Wall]). I used that node to filter Basic walls and Curtain Walls, how can I do that in another way?

**Comment by andydandy74** [comment]
When migrating Clockwork to 0.8, I deprecated quite a few nodes like ```WallType.KindIsCurtainWall``` that would return booleans (see a complete list here: https://github.com/CAAD-RWTH/ClockworkForDynamo/wiki/Deprecated-Nodes#nodes-not-migrated-to-clockwork-for-dynamo-082). Using string comparison, the remaining base nodes like ```WallType.Kind``` can still be utilized as filtering devices - but I get to maintain a lot less nodes... ;-)
Here's how you would do the filtering:
![filterbywallkind](https://cloud.githubusercontent.com/assets/3014437/11020288/a69d95d0-861a-11e5-85dd-57f77fba60dd.PNG)

**Comment by arkdanielnielsen** [comment]
Thanks! Worked perfectly ;)
