### ISSUE TITLE
View.Plane not working properly

### ISSUE THREAD

**Issue by madeforworship** [CAAD-RWTH/ClockworkForDynamo#80]
Hello, the physical location of the view.plane node doesn't seem to work properly.  Create a square room.  Put an elevation in the room.  Use the view.plane node to get the plane of the elevation view.  Notice in 0.8.2 that the plane is offset from it's actually location in dynamo and actually causes other downstream items like plane.origin to be wrong.  In 0.9.0, the plane also seems to be in the wrong place in the "Z" axis.

**Comment by andydandy74** [comment]
@madeforworship - Sorry, but I can't reproduce what you are describing. The ```View.Plane``` node retrieves its data directly from the Revit API (or more precisely: the ```Origin``` and ```ViewDirection``` properties of a given ```View``` object) and subsequently uses native Dynamo / DesignScript functionality to create a plane based on those properties - so there is not really a lot of stuff that can go wrong. Perhaps you could share a (purged) model along with a description of the expected plane properties?

**Comment by andydandy74** [comment]
Also, just to make sure: Are you using the new Clockwork packages for 0.8.2 and 0.9.x?

**Comment by madeforworship** [comment]
Hey Andreas,

Attached are some test files with a screenshot.  it seems hit or miss.
I've tried all sorts of things.  If I get an elevation that works, and copy
it, it continues to work best I can tell.  However, the majority of the
time if I place an elevation it doesn't work right.  I'm not sure if this
is related to the Revit file or what but maybe you will be able to see
something I'm not.  Also, I'm using 0.9.x right now.

Thanks,

Josh

**Comment by madeforworship** [comment]
https://www.dropbox.com/s/vak2nn320xsjs0v/View%20Plane%20Dynamo%20Issue.zip?dl=0

**Comment by madeforworship** [comment]
https://www.dropbox.com/s/vak2nn320xsjs0v/View%20Plane%20Dynamo%20Issue.zip?dl=0

**Comment by andydandy74** [comment]
Josh, I ran a test on your model and I could reproduce your issue.
It does seem completely arbitrary and I'm afraid I do not have a solution for it.
As I explained above, I am just using standard Revit API methods to retrieve the data so my best guess is that there is something off in how the Revit API calculates or returns the origin of an elevation. 
As this is something I definitely cannot fix, I can only recommend using this with section views instead as they seem to report their roigin correctly.

**Comment by madeforworship** [comment]
Thanks Andreas.  I'm reaching out to Autodesk support to see if we can get some eyes on this issue.  I've shared the link to this page with them as well.  I will follow up as I hear more.

**Comment by kronz** [comment]
Hi all,
in discussion with the Revit API dev team:  "the view origin is not related to the location of the elevation marker.  Elevation markers maintain their own position unrelated to the view, but we do not seem to expose that value in the API. "  View origin does not appear to be related to anything recognizable or useful and I recommend not using it.

**Comment by dimven** [comment]
I understand that this is not an officially supported feature, yet I've relied on this work-flow before.

I had a quick look at the file. Was it updated from an older version of Revit? ( think 2013 and back) I suspect that the elevation marker family got corrupted somewhere along the way during the multiple updates. To test this out, load a new elevation marker from the default template and note that the coordinates are reported correctly.

**Comment by andydandy74** [comment]
Good catch, @dimven - didn't think of checking that...

**Comment by madeforworship** [comment]
What happens though if you move the elevation tag after placement?

Josh Moore

**Comment by andydandy74** [comment]
the view origin moves with the elevation tag

**Comment by dimven** [comment]
Tho I believe that the Z coordinate will always be at 0 because the elevation marker is a view based 2d component.

**Comment by madeforworship** [comment]
In my testing in 2016 revit it appeared to be at 0 for the first level in the project.  So in my project it was at 0 even though my first level was at 100 but the elevation I put in at my second level which is 115 seemed to come in at 15 in Dynamo.  Easy to take care of by using a 100 ft translate but def. wierd.

Thanks,

Josh Moore

**Comment by madeforworship** [comment]
by the way, yes these files were upgraded from older versions. .It's always interesting to me to see how we figure out ways to do stuff that Factory may have never thought or intended.  Thanks again all.

**Comment by madeforworship** [comment]
@kronz I did my own test as well and confirmed what @andydandy74 tested.  In a brand new revit file, the origin point using the view.plane node does properly move when moving the view extents around.  It doesn't seem to be working off the tag itself, but actually point "plane" that is generated.  When I move that alone, and leave the tag in place, the origin still updates properly in XY space.  Z space is still an odd issue, but that seems resolvable in my testing.  Thanks for looking into this.
