### ISSUE TITLE
Q/Wish - FamilyType.SetCompoundLayerMaterial

### ISSUE THREAD

**Issue by arkdanielnielsen** [CAAD-RWTH/ClockworkForDynamo#82]
Hi Andreas
I have a question or a wish for the node "FamilyType.SetCompoundLayerMaterial". I would like to change materials for more than just one Type, but a whole list of Family Types. Is it possible (properly I suppose) to modify your node to do that? If it is, what actions/lines is needed in the script to do that? Unfortunately I am not skilled enough to figure that out :/
Thanks,
Daniel

**Comment by andydandy74** [comment]
@arkdanielnielsen - Actually the node should allow this but apparently it has some replication issues.
However, using ```List.Combine``` you can still make it work:
![capture](https://cloud.githubusercontent.com/assets/3014437/11763165/b8a9ec3c-a100-11e5-9b12-bf2d3079316d.PNG)
