### ISSUE TITLE
Material node issue

### ISSUE THREAD

**Issue by ksobon** [CAAD-RWTH/ClockworkForDynamo#83]
It looks like your node will need a small upgrade here: 

![image](https://cloud.githubusercontent.com/assets/529781/11535576/72fdd002-98e2-11e5-9f57-6207bba22a28.png)

**Comment by ksobon** [comment]
Oh, its the Revit Color to DSColor node.

**Comment by ksobon** [comment]
OK, it still didn't work for the Material.Properties. Here's what I did in Python for my own use: 

```python
# Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

# Import Element wrapper extension methods
import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

dsCorePath = r'C:\Program Files\Dynamo 0.9\DSCoreNodes.dll'
clr.AddReferenceToFileAndPath(dsCorePath)

import DSCore as ds

#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

def ProcessList(_func, _list):
	return map(lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list)

def GetColor(mat):
	r = mat.Color.Red
	g = mat.Color.Green
	b = mat.Color.Blue
	return ds.Color.ByARGB(255,r,g,b)

def Unwrap(item):
	return UnwrapElement(item)

if isinstance(IN[0], list):
	elements = ProcessList(Unwrap, IN[0])
else:
	elements = [Unwrap(IN[0])]
	
#Assign your output to the OUT variable.
OUT = ProcessList(GetColor, elements)
```

**Comment by dimven** [comment]
You can also avoid python for materials and use BGR decimal values instead:
![2015-12-03_00-09-02](https://cloud.githubusercontent.com/assets/7148394/11536164/394fc70a-9952-11e5-9e55-5c60a5a9099f.png)

**Comment by ksobon** [comment]
@dimven yeah I saw that initial Color value is displayed in decimal. Revit is sooo strange. :-) Nice one!

**Comment by andydandy74** [comment]
@ksobon - are you sure you are using a current version of Clockwork? It works fine for me with both the 0.8.2 and 0.9.x versions of Clockwork.

**Comment by andydandy74** [comment]
I am closing this for now. Feel free to re-open.
