### ISSUE TITLE
Element.Level does not work for structural framing instances

### ISSUE THREAD

**Issue by dimven** [CAAD-RWTH/ClockworkForDynamo#84]
The general consensus is that the best way to get the level of framing elements is to extract the "Reference Level" parameter. 

Also have you experienced performance issues with this node? I experienced a slow-down in a particular project, with a large array of about 3k objects (i believe it was structural foundation slabs). The same happened when extracting the element name. I suspect the nested exception catches might have something to do with it, however it might have been the particular file.

**Comment by andydandy74** [comment]
This will be in the next release...
