### ISSUE TITLE
List.ReplaceNull does not work

### ISSUE THREAD

**Issue by mdengusiak** [CAAD-RWTH/ClockworkForDynamo#89]
I run list and use "" as replacment byt my list still contain nulls,
would love to attach image but can not paste here

**Comment by mdengusiak** [comment]
see my post at http://dynamobim.org/forums/topic/list-replace-nulls-with/

**Comment by andydandy74** [comment]
@mdengusiak - This was filed as an issue here (#55) some time ago, but a fix has been provided in the meantime. Looking at the forum post, it looks like your issue has been sorted out by @ksobon in any case. I am closing this for now, but feel free to re-open.
